name: build new rules from functions
on:
  push:
    branches: [main]
    paths: ["*.ruel", .github/workflows/build_new_rules.yml]
jobs:
  build-rules:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.x
      - name: install Nutshell
        run: |
          python3 -m pip install -U pip
          gh repo clone supposedly/nutshell
      - name: build rules
        run: python3 build-new-rules.py 
      - name: remove Nutshell folder
        run: rm -rf nutshell/
      - name: commit changes # copied from ad-m/github-push-action
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "built new rules" -a
      - name: push fetched files
        uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
